# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.16.1

pipelines:
   branches:
   
     default:
     #production:
       - step:
           #deployment: master
           #master:

           caches:
             - node
           script:
             - npm init --yes
             - ls -al #checking the package.json exists in current directory
             - npm install
             #- npm run build
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git    staging:master --force
